name: Docker Image CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKERHUB_REPO: sharpscontainer/dd-client-nc
      IMAGE_TAG: 0.0.1 # TODO - automate
    permissions:
      contents: read,write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKERHUB_REPO }}:latest

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: ${{ env.IMAGE_TAG }}
          generateReleaseNotes: true
          allowUpdates: true
          
